version: "3.7"
services:
  postgres:
    image: postgres:11
    container_name: db-test
    ports:
      - 5432:5432
    volumes:
      - ./initdb/scripts:/docker-entrypoint-initdb.d
      - ./initdb/csv:/tmp
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=password
  test:
    image: jaehyeon/paranuara-challenge
    container_name: api-test
    depends_on:
      - postgres
    entrypoint:
      - python
    command: >
      -m 
      pytest 
      --cov=src 
      --cov-report=term-missing 
      --cov-config=.coveragerc 
      tests/ 
      -rsxv
    volumes:
      - ./:/home/app
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST=postgres
