version: "3.7"
services:
  postgres:
    image: postgres:11
    container_name: db
    ports:
      - 5432:5432
    volumes:
      - ./initdb/scripts:/docker-entrypoint-initdb.d
      - ./initdb/csv:/tmp
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=password
  app:
    image: jaehyeon/paranuara-challenge
    container_name: api
    depends_on:
      - postgres
    command: >
      main:app
      --host=0.0.0.0
      --port=8000
      --reload
    ports:
      - 8000:8000
    volumes:
      - ./:/home/app
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST=postgres
